//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20160805
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureWorksDW2012Entities : DbContext
    {
        public AdventureWorksDW2012Entities()
            : base("name=AdventureWorksDW2012Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DimAccount> DimAccount { get; set; }
        public DbSet<DimCurrency> DimCurrency { get; set; }
        public DbSet<DimCustomer> DimCustomer { get; set; }
        public DbSet<DimDate> DimDate { get; set; }
        public DbSet<DimDepartmentGroup> DimDepartmentGroup { get; set; }
        public DbSet<DimEmployee> DimEmployee { get; set; }
        public DbSet<DimGeography> DimGeography { get; set; }
        public DbSet<DimOrganization> DimOrganization { get; set; }
        public DbSet<DimProduct> DimProduct { get; set; }
        public DbSet<DimProductCategory> DimProductCategory { get; set; }
        public DbSet<DimProductSubcategory> DimProductSubcategory { get; set; }
        public DbSet<DimPromotion> DimPromotion { get; set; }
        public DbSet<DimReseller> DimReseller { get; set; }
        public DbSet<DimSalesReason> DimSalesReason { get; set; }
        public DbSet<DimSalesTerritory> DimSalesTerritory { get; set; }
        public DbSet<DimScenario> DimScenario { get; set; }
        public DbSet<FactAdditionalInternationalProductDescription> FactAdditionalInternationalProductDescription { get; set; }
        public DbSet<FactCallCenter> FactCallCenter { get; set; }
        public DbSet<FactCurrencyRate> FactCurrencyRate { get; set; }
        public DbSet<FactFinance> FactFinance { get; set; }
        public DbSet<FactInternetSales> FactInternetSales { get; set; }
        public DbSet<FactProductInventory> FactProductInventory { get; set; }
        public DbSet<FactResellerSales> FactResellerSales { get; set; }
        public DbSet<FactSalesQuota> FactSalesQuota { get; set; }
        public DbSet<FactSurveyResponse> FactSurveyResponse { get; set; }
        public DbSet<PlayerSet> PlayerSet { get; set; }
        public DbSet<ProspectiveBuyer> ProspectiveBuyer { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<DatabaseLog> DatabaseLog { get; set; }
    }
}
